import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box } from "@mui/system";
import { Container, Divider, Toolbar, Typography } from "@mui/material";
import Button from "@mui/material/Button";
import DrawerAppBar from "@/components/Appbar";
import Intro from "./Home/Intro";
import theme from "@/src/theme";
import Features from "./Home/Features";
import Design from "./Home/Design";
import FetchedItems from "@/firebaseConfig";
import Comments from "@/UI/Comments";

export default function Home() {
  // FetchedItems
  return (
    <>
      <Head>
        <title>Animation UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ position: "relative"}}>
        <DrawerAppBar />
        <Intro />
        <Features />
        <Design/>
        <Comments/>
      </Box>
    </>
  );
}
